require 'aims_project'

load 'config/tasks.rb'

# The name of this project
set :project_name, '__PROJECT_NAME__'

# The following settings apply to calculations occuring on the remote host

# The base directory on the remote host
set :remote_project_dir, 'AimsProjects'

# Query the user for the number of parallel nodes when queueing calculations
set(:nodes) {Capistrano::CLI.ui.ask("How many compute nodes?: ")}

# The memory for each calculation
set :memory, 1024

# The time limit for each calculation
set :time, 24

# Set the qstat command
set :qstat_cmd, "qstat -u jns"

# The qsub command to execute
# aims_script is predefined to be 'aims.sh', if this is unsuitable
# it can be reset with: set :aims_script, 'foo'
set(:qsub) { 
  "parallel.q -n #{nodes} -d #{memory} -t #{time} -ns -k #{aims_script}; qsub -notify #{aims_script}.cmd"
}

# The remote host for data transfer of large files 
role :data_transfer, "Your Data Transfer Server Here"
# The remote host for job submission
role :queue_submission, "Your Compute Cluster Server Here"
